trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: gitmirror@0
  inputs:
    GitRepoUrl: 'https://4gauip7c4de2fjjbuq5oll4ap5r6fkzsw3vulmpsdsoyoob7ugca@dev.azure.com/cecchinn/InvestorCenter/_git/InvestorCenter.nicholas.cecchin'
