trigger:
- '*'//This pipeline will run whenever you push an update to the GitHub repo

pool:
  vmImage: 'windows-latest'

steps:
- task: gitmirror@0//You can install this task in marketplace
  inputs:
    GitRepoUrl: 'https://dev.azure.com/cecchinn/InvestorCenter/_git/InvestorCenter.nicholas.cecchin'//This is the URL of Azure Repo, you need to add a personal access token in the URL
